name: Build APK on push to Main branch
run-name: ${{ github.actor }} builds apk
on:
  push:
    branches:
      - main
jobs:
  build-apk:
    run-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'
      - name: Build APK
        run: flutter build apk
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: build/app/outputs/flutter-apk/app-debug.apk